enabled: true

prometheus:
  endpoint: /metrics
  port: 8080

metrics:
  internal:
    ClassLoader: false
    DiskSpace: false
    FileDescriptor: false
    JvmGc: false
    JvmHeapPressure: false
    JvmInfo: false
    JvmMemory: false
    JvmThread: false
    Processor: false
    Uptime: false
  server:
    TickTimes:
      enabled: true
      ranges: [100, 200, 1200]
    TicksPerSecond: true
    ChunksLoaded: true
    Fullness: true
    PlayersOnline: true
    PlayersTotal: true
    PlayerStatistics: true
