enabled: true

prometheus:
  endpoint: /metrics
  port: 8080

tags:
  ip: false
  port: false
  name: false
  version: false
  bukkit-version: false
  motd: false
  custom-tags:
    # key: "value"

metrics:
  internal:
    ClassLoader: false
    DiskSpace: false
    FileDescriptor: false
    JvmGc: false
    JvmHeapPressure: false
    JvmInfo: false
    JvmMemory: false
    JvmThread: false
    Processor: false
    Uptime: false
  server:
    Entities: false
    TickTimes:
      enabled: false
      ranges: [ 100, 200, 1200 ]
    Chunks: false
    Players: false
    PlayerStatistics: false
